from enum import Enum
import collections

PRICE = "OkexSensor_swap/candle60s:BTC-USD-SWAP_close"
ASK_PRICE = 'OkexSensor_swap/depth5:BTC-USD-SWAP_ask_price_0'
BID_PRICE = 'OkexSensor_swap/depth5:BTC-USD-SWAP_bid_price_0'
TIME="window"
MODEL_DIR = "./models/"


MIN_FEATURES = [
 'OkexSensor_swap/candle60s:BTC-USD-SWAP_close',
 'BinanceSensor_btcusdt@depth5_ask_price_0',
 'BinanceSensor_btcusdt@depth5_ask_price_1',
 'BinanceSensor_btcusdt@depth5_ask_price_2',
 'BinanceSensor_btcusdt@depth5_bid_price_0',
 'BinanceSensor_btcusdt@depth5_bid_price_1',
 'BinanceSensor_btcusdt@depth5_bid_price_2',
 'HuobiSensor_market.btcusdt.depth.step1_ask_price_0',
 'HuobiSensor_market.btcusdt.depth.step1_ask_price_1',
 'HuobiSensor_market.btcusdt.depth.step1_ask_price_2',
 'HuobiSensor_market.btcusdt.depth.step1_bid_price_0',
 'HuobiSensor_market.btcusdt.depth.step1_bid_price_1',
 'HuobiSensor_market.btcusdt.depth.step1_bid_price_2',
 'HuobiSensor_market.btcusdt.kline.1min_close',
 'HuobiSensor_market.btcusdt.kline.1min_high',
 'HuobiSensor_market.btcusdt.kline.1min_low',
 'HuobiSensor_market.btcusdt.kline.1min_open',
 'OkexSensor_spot/candle60s:BTC-USDT_close',
 'OkexSensor_spot/candle60s:BTC-USDT_high',
 'OkexSensor_spot/candle60s:BTC-USDT_low',
 'OkexSensor_spot/candle60s:BTC-USDT_open',
 'OkexSensor_spot/depth5:BTC-USDT_ask_price_0',
 'OkexSensor_spot/depth5:BTC-USDT_ask_price_1',
 'OkexSensor_spot/depth5:BTC-USDT_ask_price_2',
 'OkexSensor_spot/depth5:BTC-USDT_bid_price_0',
 'OkexSensor_spot/depth5:BTC-USDT_bid_price_1',
 'OkexSensor_spot/depth5:BTC-USDT_bid_price_2',
 'OkexSensor_spot/ticker:BTC-USDT_high_24h',
 'OkexSensor_spot/ticker:BTC-USDT_last',
 'OkexSensor_spot/ticker:BTC-USDT_low_24h',
 'OkexSensor_spot/ticker:BTC-USDT_open_24h',
 'OkexSensor_swap/candle60s:BTC-USD-SWAP_high',
 'OkexSensor_swap/candle60s:BTC-USD-SWAP_low',
 'OkexSensor_swap/candle60s:BTC-USD-SWAP_open',
 'OkexSensor_swap/depth5:BTC-USD-SWAP_ask_price_0',
 'OkexSensor_swap/depth5:BTC-USD-SWAP_ask_price_1',
 'OkexSensor_swap/depth5:BTC-USD-SWAP_ask_price_2',
 'OkexSensor_swap/depth5:BTC-USD-SWAP_bid_price_0',
 'OkexSensor_swap/depth5:BTC-USD-SWAP_bid_price_1',
 'OkexSensor_swap/depth5:BTC-USD-SWAP_bid_price_2',
 'OkexSensor_swap/ticker:BTC-USD-SWAP_high_24h',
 'OkexSensor_swap/ticker:BTC-USD-SWAP_low_24h',
 'ind_rsi',
 'ind_mfi',
 'ind_tsi',
 'ind_uo',
 'ind_ao',
 'ind_macd_diff',
 'ind_vortex_pos',
 'ind_vortex_neg',
 'ind_vortex_diff',
 'ind_trix',
 'ind_mass_index',
 'ind_cci',
 'ind_dpo',
 'ind_kst',
 'ind_kst_sig',
 'ind_kst_diff',
 'ind_aroon_up',
 'ind_aroon_down',
 'ind_aroon_ind',
 'ind_bbh',
 'ind_bbl',
 'ind_bbm',
 'ind_bbhi',
 'ind_bbli',
 'ind_kchi',
 'ind_kcli',
 'ind_dchi',
 'ind_dcli',
 'ind_adi',
 'ind_obv',
 'ind_cmf',
 'ind_fi',
 'ind_em',
 'ind_vpt',
 'ind_nvi',
 'ind_dr',
 'ind_dlr',
 'ind_ma50',
 'ind_ma100',
 'ind_26ema',
 'ind_12ema',
 'ind_macd',
 'ind_100sd',
 'ind_upper_band',
 'ind_lower_band',
 'ind_ema',
 'ind_momentum'
]


FEATURES = [
 'OkexSensor_swap/candle60s:BTC-USD-SWAP_close',
 'BinanceSensor_btcusdt@depth5_ask_price_0',
 'BinanceSensor_btcusdt@depth5_ask_price_1',
 'BinanceSensor_btcusdt@depth5_ask_price_2',
 'BinanceSensor_btcusdt@depth5_ask_quantity_0',
 'BinanceSensor_btcusdt@depth5_ask_quantity_1',
 'BinanceSensor_btcusdt@depth5_ask_quantity_2',
 'BinanceSensor_btcusdt@depth5_bid_price_0',
 'BinanceSensor_btcusdt@depth5_bid_price_1',
 'BinanceSensor_btcusdt@depth5_bid_price_2',
 'BinanceSensor_btcusdt@depth5_bid_quantity_0',
 'BinanceSensor_btcusdt@depth5_bid_quantity_1',
 'BinanceSensor_btcusdt@depth5_bid_quantity_2',
 'HuobiSensor_market.btcusdt.depth.step1_ask_price_0',
 'HuobiSensor_market.btcusdt.depth.step1_ask_price_1',
 'HuobiSensor_market.btcusdt.depth.step1_ask_price_2',
 'HuobiSensor_market.btcusdt.depth.step1_ask_quantity_0',
 'HuobiSensor_market.btcusdt.depth.step1_ask_quantity_1',
 'HuobiSensor_market.btcusdt.depth.step1_ask_quantity_2',
 'HuobiSensor_market.btcusdt.depth.step1_bid_price_0',
 'HuobiSensor_market.btcusdt.depth.step1_bid_price_1',
 'HuobiSensor_market.btcusdt.depth.step1_bid_price_2',
 'HuobiSensor_market.btcusdt.depth.step1_bid_quantity_0',
 'HuobiSensor_market.btcusdt.depth.step1_bid_quantity_1',
 'HuobiSensor_market.btcusdt.depth.step1_bid_quantity_2',
 'HuobiSensor_market.btcusdt.kline.1min_amount',
 'HuobiSensor_market.btcusdt.kline.1min_close',
 'HuobiSensor_market.btcusdt.kline.1min_count',
 'HuobiSensor_market.btcusdt.kline.1min_high',
 'HuobiSensor_market.btcusdt.kline.1min_low',
 'HuobiSensor_market.btcusdt.kline.1min_open',
 'HuobiSensor_market.btcusdt.kline.1min_vol',
 'OkexSensor_spot/candle60s:BTC-USDT_close',
 'OkexSensor_spot/candle60s:BTC-USDT_high',
 'OkexSensor_spot/candle60s:BTC-USDT_low',
 'OkexSensor_spot/candle60s:BTC-USDT_open',
 'OkexSensor_spot/candle60s:BTC-USDT_volume',
 'OkexSensor_spot/depth5:BTC-USDT_ask_price_0',
 'OkexSensor_spot/depth5:BTC-USDT_ask_price_1',
 'OkexSensor_spot/depth5:BTC-USDT_ask_price_2',
 'OkexSensor_spot/depth5:BTC-USDT_ask_quantity_0',
 'OkexSensor_spot/depth5:BTC-USDT_ask_quantity_1',
 'OkexSensor_spot/depth5:BTC-USDT_ask_quantity_2',
 'OkexSensor_spot/depth5:BTC-USDT_bid_price_0',
 'OkexSensor_spot/depth5:BTC-USDT_bid_price_1',
 'OkexSensor_spot/depth5:BTC-USDT_bid_price_2',
 'OkexSensor_spot/depth5:BTC-USDT_bid_quantity_0',
 'OkexSensor_spot/depth5:BTC-USDT_bid_quantity_1',
 'OkexSensor_spot/depth5:BTC-USDT_bid_quantity_2',
 'OkexSensor_spot/ticker:BTC-USDT_base_volume_24h',
 'OkexSensor_spot/ticker:BTC-USDT_best_ask',
 'OkexSensor_spot/ticker:BTC-USDT_best_bid',
 'OkexSensor_spot/ticker:BTC-USDT_high_24h',
 'OkexSensor_spot/ticker:BTC-USDT_last',
 'OkexSensor_spot/ticker:BTC-USDT_low_24h',
 'OkexSensor_spot/ticker:BTC-USDT_open_24h',
 'OkexSensor_spot/ticker:BTC-USDT_quote_volume_24h',
 'OkexSensor_swap/candle60s:BTC-USD-SWAP_high',
 'OkexSensor_swap/candle60s:BTC-USD-SWAP_low',
 'OkexSensor_swap/candle60s:BTC-USD-SWAP_open',
 'OkexSensor_swap/candle60s:BTC-USD-SWAP_volume',
 'OkexSensor_swap/depth5:BTC-USD-SWAP_ask_price_0',
 'OkexSensor_swap/depth5:BTC-USD-SWAP_ask_price_1',
 'OkexSensor_swap/depth5:BTC-USD-SWAP_ask_price_2',
 'OkexSensor_swap/depth5:BTC-USD-SWAP_ask_quantity_0',
 'OkexSensor_swap/depth5:BTC-USD-SWAP_ask_quantity_1',
 'OkexSensor_swap/depth5:BTC-USD-SWAP_ask_quantity_2',
 'OkexSensor_swap/depth5:BTC-USD-SWAP_bid_price_0',
 'OkexSensor_swap/depth5:BTC-USD-SWAP_bid_price_1',
 'OkexSensor_swap/depth5:BTC-USD-SWAP_bid_price_2',
 'OkexSensor_swap/depth5:BTC-USD-SWAP_bid_quantity_0',
 'OkexSensor_swap/depth5:BTC-USD-SWAP_bid_quantity_1',
 'OkexSensor_swap/depth5:BTC-USD-SWAP_bid_quantity_2',
 'OkexSensor_swap/ticker:BTC-USD-SWAP_best_ask',
 'OkexSensor_swap/ticker:BTC-USD-SWAP_best_bid',
 'OkexSensor_swap/ticker:BTC-USD-SWAP_high_24h',
 'OkexSensor_swap/ticker:BTC-USD-SWAP_last',
 'OkexSensor_swap/ticker:BTC-USD-SWAP_low_24h',
 'ind_rsi',
 'ind_mfi',
 'ind_tsi',
 'ind_uo',
 'ind_ao',
 'ind_macd_diff',
 'ind_vortex_pos',
 'ind_vortex_neg',
 'ind_vortex_diff',
 'ind_trix',
 'ind_mass_index',
 'ind_cci',
 'ind_dpo',
 'ind_kst',
 'ind_kst_sig',
 'ind_kst_diff',
 'ind_aroon_up',
 'ind_aroon_down',
 'ind_aroon_ind',
 'ind_bbh',
 'ind_bbl',
 'ind_bbm',
 'ind_bbhi',
 'ind_bbli',
 'ind_kchi',
 'ind_kcli',
 'ind_dchi',
 'ind_dcli',
 'ind_adi',
 'ind_obv',
 'ind_cmf',
 'ind_fi',
 'ind_em',
 'ind_vpt',
 'ind_nvi',
 'ind_dr',
 'ind_dlr',
 'ind_ma50',
 'ind_ma100',
 'ind_26ema',
 'ind_12ema',
 'ind_macd',
 'ind_100sd',
 'ind_upper_band',
 'ind_lower_band',
 'ind_ema',
 'ind_momentum'
]

EVALUATION_INTERVALS = [6,18,30,42,54]

class EvalInterval(Enum):
   ONE_MINUTE = 6
   THREE_MINUTES = 18
   FIVE_MINUTES = 30
   TEN_MINUTES = 60
   FIFTEEN_MINUTES = 90
   

Dist = collections.namedtuple(
    'Dist', 
    [
    'short',
    'flat',
    'long',
    ]
)

Account = collections.namedtuple(
    'Account', 
    [
    'equity',
    'margin',
    'margin_frozen',
    'margin_ratio',
    'realized_pnl',
    'unrealized_pnl',
    'total_available_balance',
    'long_avail_position', # positions available to be closed
    'long_avg_cost',
    'long_leverage',
    'long_liquidation_price',
    'long_margin',
    'long_position',
    'long_realized_pnl',
    'long_settlement_price',
    'short_avail_position',
    'short_avg_cost',
    'short_leverage',
    'short_liquidation_price',
    'short_margin',
    'short_position',
    'short_realized_pnl',
    'short_settlement_price',
    'rate_limited',
    'cost',
    'delta'
    ]
)

Info = collections.namedtuple(
    'Info',
    list(Account._fields)+[
        'current_price',
        'action',
        'consec_decay',
        'reward'
    ]
)